
# Designated language. https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js

env:
  global:
    - GitHub_REF:  github.com/shiliangL/topevery-element-ui.git

# Install dependence
install:
  - npm install

# Cache the node_modules folder and don't need to download and install all npm packages every time.
# cache:
#   directories:
#     - node_modules
    
# Specify the node version.
node_js:
  - "11"
  - "10"
  - "9"

branches:
  only:
    - /.*/

stages:
  - build doc

jobs:
  include:
    - stage: build doc
      script:
        - npm run build:docs
        - git add .
        - git commit -m "code update"
        - git push --force --quiet "https://${CI_TOKEN}@${GitHub_REF}" master:master

after_success:
  - bash <(curl -s https://codecov.io/bash)  
      
# Configure to send notifications when the build fails. https://docs.travis-ci.com/user/notifications

notifications:
  webhooks:
    urls:
      - https://www.travisbuddy.com/
    on_success: never # Successful build does not send mail.
    on_failure: always # Build failure always sends a message.